### ISSUE TITLE
tests fail on big-endian systems like s390x

### ISSUE THREAD

**Issue by mr-c** [jkbonfield/htscodecs#2]
https://buildd.debian.org/status/fetch.php?pkg=htscodecs&arch=s390x&ver=0.5-2&stamp=1581614316&raw=0

Previously https://github.com/jkbonfield/io_lib version 1.14.11 did build and run on s390x

If you want, I can send a PR to add s390x to your travis CI configuration once this is fixed.

**Comment by jkbonfield** [comment]
This should now be fixed in master, along with a s390x travis config.  Please let me know if it's working for you.

**Comment by mr-c** [comment]
I can confirm, thanks @jkbonfield !

**Comment by jkbonfield** [comment]
There's a new problem in io_lib itself too, to do with CRAM 3.1 and CRAM 4.0.  I'm investigating that now.  (See https://travis-ci.org/jkbonfield/io_lib/jobs/651961118?utm_medium=notification&utm_source=github_status)

**Comment by mr-c** [comment]
@jkbonfield Thanks! Yeah, we see that as well https://buildd.debian.org/status/fetch.php?pkg=staden-io-lib&arch=s390x&ver=1.14.12-1%7Er0&stamp=1582041253&raw=0
