### ISSUE TITLE
Unaligned access in rANS_static4x16pr

### ISSUE THREAD

**Issue by daviesrob** [jkbonfield/htscodecs#4]
`rans_compress_bound_4x16()` can return an odd number, resulting in [`ptr` getting an odd address](https://github.com/jkbonfield/htscodecs/blob/3d753140/htscodecs/rANS_static4x16pr.c#L463).  After that every attempt to store data by `RansEncPutSymbol()` will be to an unaligned address, which is undesirable as it will make some of the memory accesses slower.  Presumably making `rans_compress_bound_4x16()` always return an even number would re-align all of the writes correctly.

There's a similar problem on the reading side if the [frequency table is an odd number of bytes long](https://github.com/jkbonfield/htscodecs/blob/3d753140/htscodecs/rANS_static4x16pr.c#L590).  Unfortunately there's probably not much that can be done about that.  It does cause some annoying noise from undefined behaviour sanitizer in `RansDecRenormSafe()` though, and it would be good if that could be silenced somehow.  The sanitizer doesn't notice anything earlier due to `RasDecRenorm()` being written in assembler which means it escapes sanitization.

**Comment by jkbonfield** [comment]
How are you getting these sanitizer failures?  I've just rebuilt and tested it all with CC="gcc -fsanitize=undefined" and it passes.

It may help if I knew how to reproduce the problems in order to validate I've fixed them.
